"""Autoregressive Transformer prior over the VQ codebook index sequences.

The grouped VQ bottleneck partitions each shape latent into a fixed-length
sequence of G discrete tokens drawn from a codebook of size K.  This module
models the joint distribution over these token sequences:

    p(z^q) = prod_{g=1}^{G}  p(c^g | c^1, ..., c^{g-1})

Architecture (Figure 5 in the paper):
    - Learned token embeddings for K codebook indices + one BOS token.
    - Learned positional encodings over the G token positions.
    - 3 causal (masked) Transformer layers: multi-head self-attention + FFN.
    - Linear head projecting to K logits; cross-entropy training target.

At inference, novel shapes are generated by autoregressively sampling one
token at a time, then decoding the resulting index sequence through the frozen
VQ decoder back to a continuous SDF latent.
"""

import math

import torch
import torch.nn as nn
import torch.nn.functional as F


class _CausalSelfAttention(nn.Module):
    """Multi-head causal (masked) self-attention."""

    def __init__(self, d_model: int, n_heads: int, dropout: float, seq_len: int):
        super().__init__()
        assert d_model % n_heads == 0, "d_model must be divisible by n_heads"
        self.n_heads = n_heads
        self.head_dim = d_model // n_heads
        self.scale = math.sqrt(self.head_dim)

        self.qkv = nn.Linear(d_model, 3 * d_model, bias=False)
        self.out_proj = nn.Linear(d_model, d_model, bias=False)
        self.attn_drop = nn.Dropout(dropout)
        self.resid_drop = nn.Dropout(dropout)

        # Causal mask: upper triangle (excluding diagonal) is -inf.
        causal = torch.tril(torch.ones(seq_len, seq_len)).unsqueeze(0).unsqueeze(0)
        self.register_buffer("causal_mask", causal)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, T, C = x.shape
        qkv = self.qkv(x)  # [B, T, 3*C]
        q, k, v = qkv.split(C, dim=-1)  # each [B, T, C]
        # Reshape for multi-head attention.
        q = q.view(B, T, self.n_heads, self.head_dim).transpose(1, 2)  # [B, H, T, D]
        k = k.view(B, T, self.n_heads, self.head_dim).transpose(1, 2)
        v = v.view(B, T, self.n_heads, self.head_dim).transpose(1, 2)

        attn = (q @ k.transpose(-2, -1)) / self.scale  # [B, H, T, T]
        attn = attn.masked_fill(self.causal_mask[:, :, :T, :T] == 0, float("-inf"))
        attn = F.softmax(attn, dim=-1)
        attn = self.attn_drop(attn)

        out = (attn @ v).transpose(1, 2).contiguous().view(B, T, C)
        return self.resid_drop(self.out_proj(out))


class _TransformerBlock(nn.Module):
    """Pre-norm causal Transformer block: LayerNorm → Attention → LayerNorm → FFN."""

    def __init__(self, d_model: int, n_heads: int, ffn_multiplier: int, dropout: float, seq_len: int):
        super().__init__()
        self.ln1 = nn.LayerNorm(d_model)
        self.attn = _CausalSelfAttention(d_model, n_heads, dropout, seq_len)
        self.ln2 = nn.LayerNorm(d_model)
        ffn_dim = d_model * ffn_multiplier
        self.ffn = nn.Sequential(
            nn.Linear(d_model, ffn_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(ffn_dim, d_model),
            nn.Dropout(dropout),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x + self.attn(self.ln1(x))
        x = x + self.ffn(self.ln2(x))
        return x


class ARTransformerPrior(nn.Module):
    """Autoregressive Transformer prior over VQ codebook index sequences.

    Parameters
    ----------
    num_codebooks : int
        Number of VQ groups G (sequence length of each shape's token sequence).
    codebook_size : int
        Number of entries K in each codebook (vocabulary size).
    d_model : int
        Embedding and model width.
    n_heads : int
        Number of attention heads per causal layer.
    n_layers : int
        Number of causal Transformer blocks (paper uses 3).
    ffn_multiplier : int
        FFN hidden dimension = d_model * ffn_multiplier.
    dropout : float
        Dropout probability applied inside attention and FFN layers.
    """

    BOS_OFFSET: int = 1  # Reserve index 0 as BOS; codebook indices are shifted by +1.

    def __init__(
        self,
        num_codebooks: int,
        codebook_size: int,
        d_model: int = 256,
        n_heads: int = 4,
        n_layers: int = 3,
        ffn_multiplier: int = 4,
        dropout: float = 0.4,
    ):
        super().__init__()
        self.num_codebooks = num_codebooks  # G
        self.codebook_size = codebook_size  # K
        self.d_model = d_model

        # Vocabulary = K codebook entries + 1 BOS token (at index 0 after shift).
        vocab_size = codebook_size + 1  # BOS at 0, code_i at i+1

        # Sequence length for the input fed to the Transformer = G (BOS + G-1 codes).
        seq_len = num_codebooks

        self.token_emb = nn.Embedding(vocab_size, d_model)
        self.pos_emb = nn.Embedding(seq_len, d_model)

        self.blocks = nn.ModuleList(
            [
                _TransformerBlock(d_model, n_heads, ffn_multiplier, dropout, seq_len)
                for _ in range(n_layers)
            ]
        )
        self.ln_final = nn.LayerNorm(d_model)
        self.head = nn.Linear(d_model, codebook_size, bias=False)

        self._init_weights()

    # ------------------------------------------------------------------
    # Weight initialisation
    # ------------------------------------------------------------------

    def _init_weights(self) -> None:
        nn.init.normal_(self.token_emb.weight, std=0.02)
        nn.init.normal_(self.pos_emb.weight, std=0.02)
        for module in self.modules():
            if isinstance(module, nn.Linear):
                nn.init.normal_(module.weight, std=0.02)
                if module.bias is not None:
                    nn.init.zeros_(module.bias)

    # ------------------------------------------------------------------
    # Forward pass (teacher-forced, for training)
    # ------------------------------------------------------------------

    def forward(self, indices: torch.Tensor) -> torch.Tensor:
        """Compute logits for next-token prediction.

        Parameters
        ----------
        indices : LongTensor [batch, G]
            Ground-truth codebook index sequences (values in [0, K)).

        Returns
        -------
        logits : FloatTensor [batch, G, K]
            Logits over the K codebook entries for each position.
            Position g predicts c^{g+1}, matching the shifted cross-entropy
            target computed in the training loop.
        """
        B, G = indices.shape
        device = indices.device

        # Shift codebook indices by +1 to free index 0 for BOS.
        # BOS token is index 0; shifted code c is at index c+1.
        bos = torch.zeros(B, 1, dtype=torch.long, device=device)  # [B, 1]
        shifted = indices + self.BOS_OFFSET                         # [B, G], values in [1, K]
        # Input sequence: [BOS, c^1, ..., c^{G-1}]  (length G)
        x_tokens = torch.cat([bos, shifted[:, :-1]], dim=1)         # [B, G]

        positions = torch.arange(G, device=device).unsqueeze(0)     # [1, G]
        x = self.token_emb(x_tokens) + self.pos_emb(positions)      # [B, G, d_model]

        for block in self.blocks:
            x = block(x)

        x = self.ln_final(x)                                         # [B, G, d_model]
        logits = self.head(x)                                        # [B, G, K]
        return logits

    # ------------------------------------------------------------------
    # Autoregressive sampling (inference)
    # ------------------------------------------------------------------

    @torch.no_grad()
    def sample(self, n_samples: int = 1, temperature: float = 1.0, device: str = "cpu") -> torch.Tensor:
        """Autoregressively sample G codebook indices per shape.

        Parameters
        ----------
        n_samples : int
            Number of independent shape sequences to generate.
        temperature : float
            Softmax temperature. Values < 1 sharpen the distribution;
            values > 1 increase diversity.
        device : str
            Torch device.

        Returns
        -------
        indices : LongTensor [n_samples, G]
            Sampled codebook index sequences (values in [0, K)).
        """
        self.eval()
        G = self.num_codebooks
        K = self.codebook_size

        # Start with a BOS-only sequence of length 1.
        # We grow it token by token up to length G.
        generated = torch.zeros(n_samples, 1, dtype=torch.long, device=device)  # BOS tokens

        positions_all = torch.arange(G, device=device)

        for step in range(G):
            T = generated.size(1)
            # Build input: token embeddings + positional embeddings for current prefix.
            tok_idx = generated                                                   # [B, T]
            pos_idx = positions_all[:T].unsqueeze(0)                              # [1, T]
            x = self.token_emb(tok_idx) + self.pos_emb(pos_idx)                  # [B, T, d]

            for block in self.blocks:
                x = block(x)

            x = self.ln_final(x)                                                  # [B, T, d]
            logits = self.head(x[:, -1, :])                                       # [B, K]

            if temperature != 1.0:
                logits = logits / temperature
            probs = F.softmax(logits, dim=-1)
            next_token = torch.multinomial(probs, num_samples=1)                  # [B, 1]
            # next_token is a codebook index in [0, K); shift it by BOS_OFFSET for storage.
            generated = torch.cat([generated, next_token + self.BOS_OFFSET], dim=1)

        # Strip the leading BOS token, then undo the +1 shift.
        sampled = generated[:, 1:] - self.BOS_OFFSET   # [B, G], values in [0, K)
        return sampled
